server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # No se registra a sÃ­ mismo
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # Para desarrollo

spring:
  cloud:
    compatibility-verifier:
      enabled: false