services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    ports:
      - "8088:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      # Import will be triggered at startup from the path below
      KEYCLOAK_IMPORT: "/opt/keycloak/data/import/tpi-backend-realm.json"
      # Ensure Keycloak issues tokens with the internal container hostname
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: 'false'
      PROXY_ADDRESS_FORWARDING: 'true'
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./import:/opt/keycloak/data/import:ro

volumes:
  keycloak_data:
