server:
  port: ${SERVER_PORT:8083}

# URL del microservicio de logística
api:
  logistica:
    url: ${API_LOGISTICA_URL:http://localhost:8082}

spring:
  application:
    name: ms-flota # Nombre para Eureka
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flowboxdb}
    username: ${SPRING_DATASOURCE_USERNAME:flowbox_user}
    password: ${SPRING_DATASOURCE_PASSWORD:flowbox_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI:http://localhost:8088/realms/tpi-backend}
          
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Configuración de Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}