server:
  port: 8083

api:
  logistica:
    # IMPORTANTE: Apunta al microservicio local
    url: http://localhost:8082

spring:
  application:
    name: ms-flota

  datasource:
    url: jdbc:postgresql://localhost:5434/flowboxdb
    username: flowbox_user
    password: flowbox_pass

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          # Para desarrollo local, ambos apuntan a localhost
          issuer-uri: http://localhost:8088/realms/tpi-backend
          jwk-set-uri: http://localhost:8088/realms/tpi-backend/protocol/openid-connect/certs

# Eureka deshabilitado para pruebas locales
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO
    utn.backend.tpi: DEBUG