#server:
#  port: ${SERVER_PORT:8082}
#
#spring:
#  application:
#    name: ms-logistica
#  cloud:
#    compatibility-verifier:
#      enabled: false
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flowboxdb}
#    username: ${SPRING_DATASOURCE_USERNAME:flowbox_user}
#    password: ${SPRING_DATASOURCE_PASSWORD:flowbox_pass}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          # 1. ISSUER-URI: Qué string debe tener el token en el campo 'iss'.
#          # Debe coincidir EXACTAMENTE con el host público que usaste para generar el token.
#          issuer-uri: http://localhost:8088/realms/tpi-backend
#
#          # 2. JWK-SET-URI: A dónde va el contenedor a buscar las llaves públicas.
#          # Usa el nombre del servicio en docker-compose (keycloak) y el puerto interno (8080).
#          jwk-set-uri: http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs
#
#
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#
#app:
#  osrm:
#    base-url: ${APP_OSRM_BASE_URL:http://localhost:5000}
#  flota:
#    base-url: ${APP_FLOTA_BASE_URL:http://ms-flota:8083}
#  solicitudes:
#    base-url: ${APP_SOLICITUDES_BASE_URL:http://ms-solicitudes:8081}
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#
#logging:
#  level:
#    root: INFO
#    com.logistica: DEBUG