server:
  port: 8081 # Puerto específico de ms-solicitudes

spring:
  application:
    name: ms-solicitudes

  datasource:
    # Apunta al puerto 5434 que expusiste en tu docker-compose
    url: jdbc:postgresql://localhost:5434/flowboxdb
    username: flowbox_user
    password: flowbox_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Mantiene la BD actualizada sin borrarla cada vez
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          # Apunta al Keycloak local en el puerto 8088
          issuer-uri: http://localhost:8088/realms/tpi-backend
          jwk-set-uri: http://localhost:8088/realms/tpi-backend/protocol/openid-connect/certs

# Eureka deshabilitado para pruebas locales directas
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO
    # Nivel DEBUG para tu paquete de código (útil para ver logs de lógica)
    com.transporte.ms_solicitudes: DEBUG